# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYRequest' do

  pod 'AFNetworking'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYRequest

  target 'LYRequestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYRequestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
